//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfred.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfred.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I 1895 testamenterte Alfred Nobel det meste av sin formue til et fond hvor inntektene skulle nyttes til å dele ut priser til dem som hvert år hadde gjort menneskeheten den største nytte – Nobelprisene. I sitt testamente etterlot Nobel ingen forklaring på hvorfor fredsprisen, i motsetning til de andre Nobelprisene, skulle utdeles av en norsk komité.
        ///Ifølge The Oxford International Encyclopedia of Peace, er fredsprisen den mest prestisjefulle utmerkelsen i verden..
        /// </summary>
        internal static string AlfredNobelDialog_AdditionalInformation {
            get {
                return ResourceManager.GetString("AlfredNobelDialog_AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobel var tredje sønn av Immanuel Nobel (1801–1872) og familien bodde i Stockholm til Alfred var åtte år gammel. Da flyttet familien til St. Petersburg hvor faren hadde startet en våpenfabrikk noen år tidligere.
        ///Han gikk ikke på skole, men fikk privatundervisning av gode lærere og behersket snart fire fremmedspråk (russisk, engelsk, tysk og fransk) og viste store evner i kjemi.
        ///I 1863 flyttet han tilbake til Sverige og begynte å arbeide som kjemiker ved farens verksted i Helenborg. Han videreutviklet spre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlfredNobelDialog_InformationText {
            get {
                return ResourceManager.GetString("AlfredNobelDialog_InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string AlfredNobelDialog_WantMore_Choice1 {
            get {
                return ResourceManager.GetString("AlfredNobelDialog_WantMore_Choice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nei.
        /// </summary>
        internal static string AlfredNobelDialog_WantMore_Choice2 {
            get {
                return ResourceManager.GetString("AlfredNobelDialog_WantMore_Choice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vil du vite enda mer om Alfred Nobel?.
        /// </summary>
        internal static string AlfredNobelDialog_WantMore_Text {
            get {
                return ResourceManager.GetString("AlfredNobelDialog_WantMore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, det kan jeg!.
        /// </summary>
        internal static string PeacePrizeWinnersDialog_AskForUserData_Choice1 {
            get {
                return ResourceManager.GetString("PeacePrizeWinnersDialog_AskForUserData_Choice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nei, takk!.
        /// </summary>
        internal static string PeacePrizeWinnersDialog_AskForUserData_Choice2 {
            get {
                return ResourceManager.GetString("PeacePrizeWinnersDialog_AskForUserData_Choice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi vil gjerne vite mer om deg, kan du svare på et par spørsmål?.
        /// </summary>
        internal static string PeacePrizeWinnersDialog_AskForUserData_Text {
            get {
                return ResourceManager.GetString("PeacePrizeWinnersDialog_AskForUserData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visste du at {0} vant nobels fredspris det året du ble født?.
        /// </summary>
        internal static string PeacePrizeWinnersDialog_Result {
            get {
                return ResourceManager.GetString("PeacePrizeWinnersDialog_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vite mer om Alfred Nobel.
        /// </summary>
        internal static string RootDialog_Welcome_Choice1 {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Choice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vite mer om vinnere av Nobels fredspris.
        /// </summary>
        internal static string RootDialog_Welcome_Choice2 {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Choice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm...det der forsto jeg ikke helt..
        /// </summary>
        internal static string RootDialog_Welcome_Error {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva vil du gjøre først?.
        /// </summary>
        internal static string RootDialog_Welcome_QuestionText {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei!.
        /// </summary>
        internal static string RootDialog_Welcome_QuestionTitle {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei {0}, hvilket år ble du født?.
        /// </summary>
        internal static string UserInformationDialog_BirthYearQuestion {
            get {
                return ResourceManager.GetString("UserInformationDialog_BirthYearQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvilket land kommer du fra?.
        /// </summary>
        internal static string UserInformationDialog_CountryQuestion {
            get {
                return ResourceManager.GetString("UserInformationDialog_CountryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva heter du?.
        /// </summary>
        internal static string UserInformationDialog_NameQuestion {
            get {
                return ResourceManager.GetString("UserInformationDialog_NameQuestion", resourceCulture);
            }
        }
    }
}
